//
// Created by Pablo Lobato on 30/11/2023.
//

#ifndef JUANPABLOLOBATO_CASOFINALINTEGRADOR2_EJ1_H
#define JUANPABLOLOBATO_CASOFINALINTEGRADOR2_EJ1_H


class EJ1 {

};


#endif //JUANPABLOLOBATO_CASOFINALINTEGRADOR2_EJ1_H
